/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uzemgorsel03;

import javax.swing.JOptionPane;

/**
 *
 * @author Nano
 */
public class KasaToplami extends javax.swing.JFrame {

    /**
     * Creates new form KasaToplami
     */
    public KasaToplami() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jCheckBox1.setText("Pizza - 20 TL");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(60, 40, 440, 90);

        jCheckBox2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jCheckBox2.setText("Burger - 15 TL");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(60, 130, 440, 90);

        jCheckBox3.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jCheckBox3.setText("Tost - 10 TL");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(60, 220, 440, 90);

        jButton1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jButton1.setText("Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 340, 230, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        float ucret = 0;
        String mesaj = "";
        
        if (jCheckBox1.isSelected()){
            ucret += 20;
            mesaj += "Pizza - 20 TL\n";
        }
        if (jCheckBox2.isSelected()){
            ucret += 15;
            mesaj += "Burger - 15 TL\n";
        }
        if (jCheckBox3.isSelected()){
            ucret += 10;
            mesaj += "Tost - 10 TL\n";  
        }
        mesaj += "------------\n";
        JOptionPane.showMessageDialog(this, mesaj + "Toplam Ucretiniz : " + ucret + " TL");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasaToplami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasaToplami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasaToplami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasaToplami.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasaToplami().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    // End of variables declaration//GEN-END:variables
}
